### ISSUE TITLE
Remove code that uses dmapfilesparser 

### ISSUE THREAD

**Issue by vargheseg** [ChimeraTK/CommandLineTools#3]
##### Current behavior with multiple dmap files in working directory:
- We use the first dmap file the dmapfiles parser picks

##### Proposed behavior:
- Do not use dmapfiles parser; this is deprecated and will be removed.
- Pick present dmap file in the working directory as the default.
- On mutiple dmap files in working directory, inform the user to pick  one.
- Let user specify dmap file in the above situation using an additional flag. (eg maybe something like  `--dmap-file`)

**Comment by killenb** [comment]
Completely implemented in e0e78c3

The conflict in case of two dmap files is resolved by naming one of them 'CommandLineTools.dmap'. This solution also works for the matlab remote tools out of the box.
